GestaoFornecedor.Web/Controllers/ContatoController.cs
using GestaoFornecedor.Core;
using GestaoFornecedor.Domain;
using System;
using System.Web.Mvc;

namespace GestaoFornecedor.Web.Controllers
{
    public class ContatoController : Controller
    {
        // GET: Contato
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateContato(Contato contato)
        {
            var service = new ContatoSvc();
            service.AdicionarContato(contato);

            return RedirectToAction("Editar", "Fornecedor", new { id = contato.FornecedorId });
        }

        public ActionResult ListaContatos(int idFornecedor)
        {
            var service = new ContatoSvc();

            return PartialView("_TabelaContato", service.ListaContatoPorFornecedor(idFornecedor));
        }

        public ActionResult EditarContato(int id)
        {
            var service = new ContatoSvc();
            Contato result = new Contato();

            result = service.GetContatoPorId(id);

            return PartialView("_EditarContato", result);
        }

        [HttpPost]
        public ActionResult EditarContato(Contato contato)
        {
            var service = new ContatoSvc();
            service.Editar(contato);

            return RedirectToAction("Editar", "Fornecedor", new { id = contato.FornecedorId });
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var service = new ContatoSvc();
            var contato = service.GetContatoPorId(Convert.ToInt32(id));

            service.Delete(Convert.ToInt32(id));

            return RedirectToAction("Editar", "Fornecedor", new { id = contato.FornecedorId });
        }
    }
}

GestaoFornecedor.Web/Controllers/FornecedorController.cs
using GestaoFornecedor.Core;
using GestaoFornecedor.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace GestaoFornecedor.Web.Controllers
{
    public class FornecedorController : Controller
    {
        FornecedorSvc _fornecedorSvc;
        FornecedorSvc FornecedorSvc
        {
            get
            {
                return _fornecedorSvc ?? (_fornecedorSvc = new FornecedorSvc());
            }
        }

        EstadoSvc _estadoSvc;
        EstadoSvc EstadoSvc
        {
            get
            {
                return _estadoSvc ?? (_estadoSvc = new EstadoSvc());
            }
        }

        // GET: Fornecedor
        public ActionResult Index()
        {
            List<Fornecedor> fornecedores = FornecedorSvc.ListaFornecedores();

            return View(fornecedores);
        }

        public ActionResult Cadastrar()
        {
            // Buscando Estados
            var listaEstados = EstadoSvc.ListaEstados();

            listaEstados.Insert(0, new Estado());
            ViewBag.Estado = new SelectList(listaEstados, "Id", "Nome");
            ViewBag.Sucesso = null;

            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Fornecedor fornecedor, string NomeContato, string Telefone, string Email)
        {
            // Buscando Estados
            var listaEstados = EstadoSvc.ListaEstados();
            ViewBag.Estado = new SelectList(listaEstados, "Id", "Nome");

            if (ModelState.IsValid)
            {
                var estruturaRetorno = FornecedorSvc.AdicionarFornecedor(fornecedor);

                if (estruturaRetorno.PossuiErro)
                    ViewBag.Erro = estruturaRetorno.Mensagem;
                else
                {
                    if (NomeContato != null &&
                        (Telefone != null || Email != null))
                    {
                        var serviceContato = new ContatoSvc();
                        Contato contato = new Contato();
                        contato.Nome = NomeContato;
                        contato.Telefone = Telefone;
                        contato.Email = Email;
                        contato.FornecedorId = FornecedorSvc.GetFornecedorPorNome(fornecedor.Nome).Id;
                        serviceContato.AdicionarContato(contato);
                        ViewBag.Sucesso = estruturaRetorno.Mensagem;
                    }
                    else
                        ViewBag.Sucesso = "Fornecedor Cadastrado Com sucesso. Contato não foi cadastrado por inconsistência nos dados";
                }                    

                return View();
            }
            
            return View("Cadastrar", fornecedor);
        }

        public ActionResult ListaCidade(string id)
        {
            var serviceCidade = new CidadeSvc();
            List<Cidade> cidades = serviceCidade.ListaCidadePorEstado(Convert.ToInt32(id));

            return Json(cidades.Select(s => new
            {
                s.Id,
                s.Nome
            }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            ViewBag.Sucesso = null;
            ViewBag.Contato = new Contato();

            var fornecedor = FornecedorSvc.GetFornecedorPorId(Convert.ToInt32(id));

            // Buscando Estados
            var listaEstados = EstadoSvc.ListaEstados();

            //listaEstados.Insert(0, new Estado());
            ViewBag.Estado = new SelectList(listaEstados, "Id", "Nome", fornecedor.Cidade.Estado.Nome);

            return View(fornecedor);
        }

        [HttpPost]
        public ActionResult Editar(Fornecedor fornecedor)
        {
            ViewBag.Contato = new Contato();

            if (ModelState.IsValid)
            {
                var estruturaRetorno = FornecedorSvc.Editar(fornecedor);
                fornecedor = FornecedorSvc.GetFornecedorPorId(fornecedor.Id);

                // Buscando Estados
                var SvcEstado = new EstadoSvc();

                ViewBag.Estado = new SelectList(EstadoSvc.ListaEstados(), "Id", "Nome", fornecedor.Cidade.Estado.Nome);

                if (estruturaRetorno.PossuiErro)
                    ViewBag.Erro = estruturaRetorno.Mensagem;
                else
                    ViewBag.Sucesso = estruturaRetorno.Mensagem;

                return View(fornecedor);
            }

            var listaEstados = EstadoSvc.ListaEstados();
            var auxFornecedor = FornecedorSvc.GetFornecedorPorId(fornecedor.Id);

            fornecedor.Cidade = auxFornecedor.Cidade;
            fornecedor.Contato = auxFornecedor.Contato;

            ViewBag.Estado = new SelectList(listaEstados, "Id", "Nome", fornecedor.Cidade.Estado.Nome);

            return View(fornecedor);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            FornecedorSvc.Delete(Convert.ToInt32(id));

            return RedirectToAction("Index");
        }
    }
}

GestaoFornecedor.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace GestaoFornecedor.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GestaoFornecedor.Web/Views/Contato/Editar.cshtml
@model GestaoFornecedor.Domain.Contato

@{
    Layout = null;
}

<!-- Modal -->
<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Editar Contato</h4>
        </div>
        @using (Html.BeginForm("EditarContato", "Contato", FormMethod.Post))
        {
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <label for="Nome">Nome</label>
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control",
                            value = "model.Nome" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        <label for="Telefone">Telefone</label>
                        @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control Telefone",
                            value = "model.Telefone" } })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="Email">E-mail</label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control",
                            @value="model.Email" } })
                        @Html.Hidden("Id", Model.Id)

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Salvar" />
                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar</button>
            </div>
        }
    </div>
</div>

GestaoFornecedor.Web/Views/Contato/_EditarContato.cshtml
@model GestaoFornecedor.Domain.Contato

<!-- Modal -->
<div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Editar Contato</h4>
        </div>
        @using (Html.BeginForm("EditarContato", "Contato", FormMethod.Post))
        {
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <label for="Nome">Nome</label>
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control",
                            value = "model.Nome" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-6">
                        <label for="Telefone">Telefone</label>
                        @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control Telefone",
                            value = "model.Telefone" } })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label for="Email">E-mail</label>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control",
                            @value="model.Email" } })
                        @Html.Hidden("Id", Model.Id)
                        @Html.Hidden("FornecedorId", Model.FornecedorId)

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Salvar" />
                <button type="button" class="btn btn-default" data-dismiss="modal">Voltar</button>
            </div>
        }
    </div>
</div>

GestaoFornecedor.Web/Views/Contato/_TabelaContato.cshtml
@model ICollection<GestaoFornecedor.Domain.Contato>

<div class="col-md-12" style="font-size: 11px !important; border: 1px solid #e6e6e6;">
    <h3 style="margin-bottom = 5px">Contatos</h3>
    <table id="tabelaContato" class="table display">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var contato in Model)
            {
                <tr>
                    <td> @contato.Nome</td>
                    <td>@contato.Email</td>
                    <td class="Telefone">@contato.Telefone</td>
                    <td>
                        <button class="btn btn-primary btn-xs editar" data-id="@contato.Id">Editar</button>
                        @Html.ActionLink("Excluir", "Delete", "Contato", new { id = contato.Id },
                             new { onclick = "return confirm('Deseja excluir o contato?');", @class = "btn btn-danger btn-xs" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        $('#tabelaContato').DataTable({
            "language": {
                "info": "Exibindo página _PAGE_ de _PAGES_",
                "infoEmpty": "Não foi encontrado registros",
                "search": "Buscar",
            },
            "scrollY": "140px",
            "scrollCollapse": true,
            "paging": false

        });
    });

    // Modal
    $(function () {
        $(".editar").click(function () {
            var id = $(this).attr("data-id");
            $("#modalContatoEdicao").load("/Contato/EditarContato?id=" + id, function () {
                $("#modalContatoEdicao").modal();
            })
        });
    })
</script>

GestaoFornecedor.Web/Views/Fornecedor/Cadastrar.cshtml
@model GestaoFornecedor.Domain.Fornecedor

@{
    ViewBag.Title = "Cadastrar";
}

<h3>Cadastrar Fornecedor</h3>

@if (ViewBag.Sucesso != null)
{
    <div class="alert alert-success alert-dismissible fade in" style="margin-top: 5px">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @ViewBag.Sucesso
    </div>
}
else if (ViewBag.Erro != null)
{
    <div class="alert alert-danger alert-dismissible fade in" style="margin-top: 5px">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @ViewBag.Erro
    </div>
}

@using (Html.BeginForm("Cadastrar", "Fornecedor", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="row">
            <div class="form-group col-md-4">
                <label for="Nome">Nome</label>
                @Html.EditorFor(fornecedor => fornecedor.Nome, new { htmlAttributes = new { @class = "form-control input-sm" } })
                @Html.ValidationMessageFor(fornecedor => fornecedor.Nome, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-offset-1 col-md-3 checkbox">
                <label for="Status">Ativo</label>
                @Html.CheckBox("Status", true)
            </div>
            <div class="form-group col-md-4">
                <label for="Estado">Estado</label>
                @Html.DropDownList("Estado", (IEnumerable<SelectListItem>)ViewBag.PriorityID, new { @class = "form-control input-sm", @id = "Estado" })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-3">
                <label for="Cidade">Cidade</label>
                <select id="CidadeId" name="CidadeId" class="form-control input-sm">
                    <option selected="selected" value=""></option>
                </select>
            </div>
            <div class="form-group col-md-3">
                <label for="DataInicioContrato">Data Inicio Contrato</label>
                <input type="text" class="form-control data input-sm" id="DataInicioContrato" name="DataInicioContrato" />
                @Html.ValidationMessageFor(fornecedor => fornecedor.DataInicioContrato, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label for="DataFinalContrato">Data Fim Contrato</label>
                <input type="text" class="form-control data input-sm" id="DataFinalContrato" name="DataFinalContrato" />
                @Html.ValidationMessageFor(fornecedor => fornecedor.DataFinalContrato, "", new { @class = "text-danger" })
            </div>
            <div class="form-group col-md-3">
                <label for="ValorMaximoPorDemanda">Valor máximo Por Demanda</label>
                @Html.EditorFor(fornecedor => fornecedor.ValorMaximoPorDemanda, new { htmlAttributes = new { @id = "ValorMaximoPorDemanda", @class = "form-control input-sm" } })
            </div>
        </div>

        <div class="row" style="font-size: 11px !important; border: 1px solid #e6e6e6; margin: 5px">
            <h3>Contato</h3>
            <div class="col-md-6">
                <label for="NomeContato">Nome</label>
                <input type="text" class="form-control input-sm" id="NomeContato" name="NomeContato" />
            </div>
            <div class="col-md-6">
                <label for="Telefone">Telefone</label>
                <input type="text" class="form-control input-sm Telefone" id="Telefone" name="Telefone" />
            </div>
            <div class="col-md-6">
                <label for="Email">Email</label>
                <input type="text" class="form-control input-sm" id="Email" name="Email" />
                <br />
            </div>
        </div>

        <div class="row">
            <input type="submit" class="btn btn-primary" value="Salvar" />
            <a href="/fornecedor/index" class="btn btn-default">Voltar</a>
        </div>
    </fieldset>
}


<asp:Content ID="Javascript" ContentPlaceHolderID="HeadContent" runat="server">
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Estado").change(function () {
                //listaCidade($(this).val());
                $("#Cidade").empty();
                listarCidades();
            });
        });
        function listarCidades() {
            $.ajax({
                'method': 'GET',
                'url': '@Url.Action("ListaCidade", "Fornecedor")',
                'type': 'application/json',
                data: {
                    id: $('#Estado').val()
                },
                success: function (response) {
                    $(response).each(function () {
                        $("#CidadeId").append("<option value='" + this.Id + "'>" + this.Nome + "</option>");
                    });
                },
                error: function () {

                }
            });
        }

        $(document).ready(function () {
            $('.data').mask('99/99/9999');
            $('#ValorMaximoPorDemanda').mask('99,99');
            $('.Telefone').mask('99-9999-9999');
        });
    </script>
</asp:Content>

GestaoFornecedor.Web/Views/Fornecedor/Editar.cshtml
@model GestaoFornecedor.Domain.Fornecedor

@{
    ViewBag.Title = "Editar";
}

<div class="row">
    <br />
    <b>Editar @Model.Nome</b>
    <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#modalContato">Novo Contato</button>
</div>
@if (ViewBag.Sucesso != null)
{
    <div class="alert alert-success alert-dismissible fade in" style="margin-top: 5px">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @ViewBag.Sucesso
    </div>
}
else if (ViewBag.Erro != null)
{
    <div class="alert alert-danger alert-dismissible fade in" style="margin-top: 5px">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @ViewBag.Erro
    </div>
}

<form action="/Fornecedor/Editar/@Model.Id" method="post">

    <div class="row">
        <div class="col-md-4 form-group">
            <label for="Nome">Nome</label>
            <input type="text" value="@Model.Nome" class="form-control input-sm" id="Nome" name="Nome" />
            @Html.ValidationMessageFor(fornecedor => fornecedor.Nome, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-offset-1 col-md-3 form-group checkbox">
            <label for="Status">Ativo</label>
            @Html.CheckBox("Status")
        </div>
        <div class="form-group col-md-4">
            <label for="Estado">Estado</label>
            @Html.DropDownList("Estado", (IEnumerable<SelectListItem>)ViewBag.PriorityID, new { @class = "form-control input-sm", @id = "Estado" })

        </div>
    </div>
    <div class="row">
        <div class="col-md-3 form-group">
            <label for="Cidade">Cidade</label>
            <select id="CidadeId" name="CidadeId" class="form-control input-sm">
                <option value="@Model.CidadeId">@Model.Cidade.Nome</option>
            </select>
        </div>
        <div class="col-md-3 form-group">
            <label for="DataInicioContrato">Data Inicio Contrato</label>
            @Html.TextBoxFor(m => m.DataInicioContrato, "{0:dd/MM/yyyy}", new { @class = "form-control input-sm data", @id = "DataInicioContrato", @name = "DataInicioContrato" })
            @Html.ValidationMessageFor(fornecedor => fornecedor.DataInicioContrato, "", new { @class = "text-danger" })

        </div>
        <div class="col-md-3 form-group">
            <label for="DataFinalContrato">Data Fim Contrato</label>
            @Html.TextBoxFor(m => m.DataFinalContrato, "{0:dd/MM/yyyy}", new { @class = "form-control input-sm data", @id = "DataFinalContrato", @name = "DataFinalContrato" })
            @Html.ValidationMessageFor(fornecedor => fornecedor.DataFinalContrato, "", new { @class = "text-danger" })

        </div>
        <div class="col-md-3 form-group">
            <label for="ValorMaximoPorDemanda">Valor máximo Por Demanda</label>
            @Html.EditorFor(fornecedor => fornecedor.ValorMaximoPorDemanda, new { htmlAttributes = new { @id = "ValorMaximoPorDemanda", @class = "form-control input-sm" } })
        </div>
    </div>
    <div class="row">
        <hr />
        <div class="col-md-6 form-group">
            <input type="submit" class="btn btn-primary" value="Salvar" />
            <a href="/fornecedor/index" class="btn btn-default">Voltar</a>
        </div>
    </div>
</form>

@if (Model.Contato.ToList().Count() > 0)
{
    @Html.Partial("~/Views/Contato/_TabelaContato.cshtml", Model.Contato)

    <div class="modal fade" id="modalContatoEdicao" role="dialog">
    </div>

}


<!-- Modal -->
<div class="modal fade" id="modalContato" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Novo Contato</h4>
            </div>
            @using (Html.BeginForm("CreateContato", "Contato", FormMethod.Post))
            {
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="Nome">Nome</label>
                            <input type="text" id="Nome" name="Nome" class="form-control" />
                        </div>
                        <div class="col-md-6">
                            <label for="Telefone">Telefone</label>
                            <input type="text" id="Telefone" name="Telefone" class="form-control Telefone" />
                            @ViewBag.Contato.Nome
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label for="Email">E-mail</label>
                            <input type="text" id="Email" name="Email" class="form-control" />
                        </div>
                    </div>
                    @Html.Hidden("FornecedorId", Model.Id)
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Salvar" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">Voltar</button>
                </div>
            }
        </div>
    </div>
</div>

<asp:Content ID="Javascript" ContentPlaceHolderID="HeadContent" runat="server">
    <script type="text/javascript">
        $(document).ready(function () {
            $("#Estado").change(function () {
                //listaCidade($(this).val());
                $("#CidadeId").empty();
                listarCidades();
            });
        });

        function listarCidades() {
            $.ajax({
                'method': 'GET',
                'url': '@Url.Action("ListaCidade", "Fornecedor")',
                'type': 'application/json',
                data: {
                    id: $('#Estado').val()
                },
                success: function (response) {
                    $(response).each(function () {
                        $("#CidadeId").append("<option value='" + this.Id + "'>" + this.Nome + "</option>");
                    });
                },

                error: function () {

                }
            });
        }
        $(document).ready(function () {
            $('.data').mask('99/99/9999');
            $('#ValorMaximoPorDemanda').mask('99,99');
            $('.Telefone').mask('99-9999-9999');
            var valor = $('#ValorMaximoPorDemanda').val();
            if (true) {

            }
        });

    </script>
</asp:Content>

GestaoFornecedor.Web/Views/Fornecedor/Index.cshtml
@model List<GestaoFornecedor.Domain.Fornecedor>

@{
    ViewBag.Title = "XYZ – Logistica e Transportes";
}


<h2>Fornecedores</h2>
<a href="/fornecedor/cadastrar" class="btn btn-success">Cadastrar</a>
<br /><br />

<div class="col-md-12">
    <table id="tabelaFornecedor" class="table display">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Estado</th>
                <th>Cidade</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var fornecedor in Model)
            {
                <tr>
                    <td> @fornecedor.Nome</td>
                    <td>@fornecedor.Cidade.Estado.Nome</td>
                    <td>@fornecedor.Cidade.Nome</td>
                    
                    @if (fornecedor.Status == true)
                    {
                        <td>Ativo</td>
                    }
                    else
                    {
                        <td>Inativo</td>
                    }
                        <td>
                            @Html.ActionLink("Editar", "Editar", new { id = @fornecedor.Id }, new { @class = "btn btn-primary" })
                            @Html.ActionLink("Excluir", "Delete", new { id = @fornecedor.Id },
                                new { onclick = "return confirm('Deseja excluir o fornecedor?');", @class = "btn btn-danger" })
                        </td>
                </tr>
            }
        </tbody>
    </table>
</div>


<!-- Modal -->
<div class="modal fade" id="ModalDelete" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Excluir</h4>
            </div>
            <div class="modal-body">
                <p>Deseja excluir o fornecedor?</p>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-default" data-dismiss="modal">Cancela</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        $('#tabelaFornecedor').DataTable({
            "language": {
                "lengthMenu": "Exibir _MENU_ por página",
                "zeroRecords": "Não foi encontrado registros",
                "info": "Exibindo página _PAGE_ de _PAGES_",
                "infoEmpty": "Não foi encontrado registros",
                "search": "Buscar",
                "paginate": {
                    "previous": "Anterior ",
                    "next": " Próxima"
                }
            }
        });
    });
</script>

GestaoFornecedor.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GestaoFornecedor.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GestaoFornecedor.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GestaoFornecedor.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryMask")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("XYZ – Logistica e Transportes", "Index", "Fornecedor", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryMask")
    @RenderSection("scripts", required: false)
</body>
</html>